name: litelearninglab
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.14.0
  flutter_card_swiper: ^7.0.1
  smooth_page_indicator: ^1.1.0
  showcaseview: ^3.0.0
  expansion_tile_group:
  cupertino_icons: ^1.0.5
  after_layout: ^1.2.0
  cloud_firestore: ^4.8.1
  firebase_auth: ^4.6.3
  intl: 0.17.0
  toast: ^0.3.0
  provider: ^6.0.5
  url_launcher: ^6.1.11
  firebase_database: ^10.2.3
  firebase_messaging: ^14.6.3
  audioplayers: ^4.1.0
  speech_to_text: ^6.1.1
  number_to_words: ^1.0.0
  sqflite: ^2.2.8+4 #no web
  shared_preferences: ^2.1.2
  flutter_tts: ^3.7.0
  animations: ^2.0.7
  flutter_inappwebview: ^5.7.2+3 #no web
  device_info: #no web
  package_info: ^2.0.2 #no web
  get: ^4.6.5
  permission_handler:
  cached_network_image: ^3.2.3
  pin_code_fields: ^7.4.0
#  flutter_statusbarcolor: ^0.2.3
  scroll_to_index: ^3.0.1
  aes_crypt_null_safe: ^2.0.2
  path_provider: ^2.0.15
  firebase_remote_config: ^4.2.3
  video_player: ^2.1.6
  chewie: ^1.8.1
  flutter_local_notifications: ^14.1.1
  firebase_analytics: ^10.4.3
  flutter_svg: ^2.0.9
  number_to_words_english: ^2.0.2
  auto_size_text: ^3.0.0

  percent_indicator: ^4.2.3
  google_fonts: ^4.0.4
  card_swiper: ^3.0.1
  upgrader:
  flutter_page_view_indicator: ^0.0.5
  card_stack_widget: ^0.1.5
  swipe_deck: ^1.0.0
  slide_switcher: ^1.1.2
  flutter_colorful_tab: ^0.1.1
  http: ^0.13.6
  json_annotation: ^4.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie:
  fl_chart: ^0.69.0
  syncfusion_flutter_charts: 20.3.61
  connectivity_plus: ^6.0.3
  flutter_user_guildance: ^2.0.7








dev_dependencies:
  build_runner: ^2.1.0
  hive_generator: ^2.0.1
  json_serializable: ^6.6.1
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/process.jpg
    - assets/images/drawerIcon.png
    - assets/images/soft.jpg
    - assets/images/ameri.jpg
    - assets/sounds/speech_to_text_listening.m4r
    - assets/sounds/speech_to_text_cancel.m4r
    - assets/sounds/speech_to_text_stop.m4r
    - assets/images/dashboard.svg
    - assets/images/about.svg
    - assets/images/calender.png
    - assets/mp4_video/video_20241022_115109_check.mp4


  fonts:
    - family: Varela
      fonts:
        - asset: assets/font/varela.ttf
    - family: Symbola
      fonts:
        - asset: assets/font/symbola.ttf
    - family: Lucida
      fonts:
        - asset: assets/font/lucida-sans-unicode.ttf
    - family: Kaushan
      fonts:
        - asset: assets/font/KaushanScript-Regular.ttf
    - family: Quicksand
      fonts:
        - asset: assets/font/Quicksand-VariableFont_wght.ttf
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 500
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Thin.ttf
          weight: 400
